# Generated by Django 4.1.7 on 2026-02-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octofit_tracker', '0002_user_fitness_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leaderboard',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='calories',
        ),
        migrations.AddField(
            model_name='activity',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='workout_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
